language: node_js
node_js:
  - “stable”
deploy:
    provider: s3
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    bucket: anitra
    acl: public_read
    local_dir:
    skip_cleanup: true
