language: node_js
node_js:
  - 8.9.4
deploy:
    provider: s3
    on:
      branch: prod
    access_key_id: $access
    secret_access_key: $secret
    bucket: anitra
    acl: public_read
    local_dir: dist
    skip_cleanup: true
